### ISSUE TITLE
received invalid response to SSL negotiation: J

### ISSUE THREAD

**Issue by orlando** [boxen/puppet-postgresql#25]
Hello, I'm getting that error when trying to create a new database using Rails.

`received invalid response to SSL negotiation: J`

Any suggestion? Thanks

**Comment by behramcelen** [comment]
you are great man :smile:

**Comment by lipelipidio** [comment]
and I'm getting the erro 
 'received invalid response to SSL negotiation: Y

MY GOD WHAT I DO!

**Comment by lipelipidio** [comment]
and I'm getting the erro 
 'received invalid response to SSL negotiation: Y

MY GOD WHAT I DO!

**Comment by lipelipidio** [comment]
Sorry I sent the same message twice

**Comment by orlando** [comment]
@lipelipidio my problem was the port, but this was 4 years ago so no idea what could be, not using boxen anymore
